name: encrypted_video_player
description: Video Player that encrypt & play video offline
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  path_provider: ^1.6.24
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  provider: ^4.3.2+2
  flutter_hls_parser: ^1.0.0
  flutter_ffmpeg: ^0.3.0
  flick_video_player: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true